version: "3.4"

services:
  migrate:
    image: money-lover:latest
    env_file: .env
    command: ["alembic", "upgrade", "head"]
    network_mode: host

  app:
    image: money-lover:latest
    ports:
      - "${DEFAULT_PORT}:${DEFAULT_PORT}"
    restart: unless-stopped
    env_file: .env
    network_mode: host
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${DEFAULT_PORT}/api/v1/healthcheck" ]
      interval: 30s
      timeout: 20s
      retries: 3
