"""empty message

Revision ID: 52be686dcbc0
Revises: f471814f11d2
Create Date: 2021-01-20 16:03:49.690400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52be686dcbc0'
down_revision = 'f471814f11d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('deleted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'deleted')
    # ### end Alembic commands ###
