"""empty message

Revision ID: 538e5dc9c310
Revises: 244cb6b2b556
Create Date: 2020-11-27 14:48:49.564883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538e5dc9c310'
down_revision = '244cb6b2b556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('date_tran', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'date_tran')
    # ### end Alembic commands ###
