"""empty message

Revision ID: 551c276c6dd6
Revises: 
Create Date: 2020-11-16 22:52:19.051458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551c276c6dd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_name'), 'wallet', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_name'), table_name='wallet')
    op.drop_table('wallet')
    # ### end Alembic commands ###
