"""empty message

Revision ID: d632ac83d11b
Revises: e0da2afb6bab
Create Date: 2020-12-29 22:42:54.551973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd632ac83d11b'
down_revision = 'e0da2afb6bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('type', sa.String(), nullable=True))
    op.create_index(op.f('ix_wallet_type'), 'wallet', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_type'), table_name='wallet')
    op.drop_column('wallet', 'type')
    # ### end Alembic commands ###
